{application,log_service,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{log_service_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[lib_log,log]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
