{application,rd_service,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{rd_service_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[heartbeat,lib_rd,rd,rd_store]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
