{application,zigbee,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{zigbee_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[zigbee_app,zigbee_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
